language: python

python:
  - 2.7

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source='.' manage.py test

after_success:
  - coveralls