language: python

python:
  - 2.7

services:
  - mysql

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_install:
  - mysql -e 'create database test_clockwork;'
  - python manage.py syncdb --noinput

script:
  - coverage run --source='.' manage.py test

after_success:
  - coveralls