# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-09 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isad', '0002_auto_20180608_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='isad',
            name='catalog_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
