"""
Django settings for clockwork project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '45lt2&5*&!qt1yi=zh03do_*)t3g4^)2cl8a()23((n&j%qfu='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
PREREQ_APP = [
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'bootstrap3',
    'django_select2',
    'widget_tweaks',
    'crispy_forms',
    'fm',
    'userena',
    'guardian',
    'easy_thumbnails'
]

PROJECT_APPS = [
    'accounts',
    'authority',
    'controlled_list',
    'dashboard',
    'archival_unit',
    'accession',
    'donor',
    'isaar',
    'isad',
    'container',
    'finding_aids',
    'mlr'
]

INSTALLED_APPS = PREREQ_APP + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'clockwork.middleware.lastmodifiedbyuser.LastModifiedMiddleware'
]

ROOT_URLCONF = 'clockwork.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
            ],
        },
    },
]

WSGI_APPLICATION = 'clockwork.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'clockwork-python',                      # Or path to database file if using sqlite3.
        # The following settings are not used with sqlite3:
        'USER': 'root',
        'PASSWORD': 'Vizipoki304',
        'HOST': 'localhost',                      # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'PORT': '',                      # Set to empty string for default.

    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False
DATETIME_FORMAT = 'N j, Y, H:i:s'

USE_TZ = True

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = '/static/'

# Bootstrap3 plugin settings
BOOTSTRAP3 = {
    # Set HTML disabled attribute on disabled fields
    'set_disabled': False,

    # Set placeholder attributes to label if no placeholder is provided
    'set_placeholder': False,

    # Class to indicate required (better to set this in your Django form)
    'required_css_class': 'required',
}

SUMMERNOTE_CONFIG = {
    'iframe': False,
    'width': '100%',
    'height': '200px',
    'disable_upload': True,
}

DATE_EXTENSIONS_OUTPUT_FORMAT_DAY_MONTH_YEAR = "Y-m-d"
DATE_EXTENSIONS_OUTPUT_FORMAT_MONTH_YEAR = "Y-m"
DATE_EXTENSIONS_OUTPUT_FORMAT_YEAR = "Y"

DATE_EXTENSIONS_DATE_INPUT_FORMATS = ("%Y-%m-%d",)
DATE_EXTENSIONS_MONTH_INPUT_FORMATS = ("%Y-%m",)
DATE_EXTENSIONS_YEAR_INPUT_FORMATS = ("%Y",)

CRISPY_TEMPLATE_PACK = 'bootstrap3'

TIME_INPUT_FORMATS = [
    '%H:%M:%S',     # '14:30:59'
    '%H:%M',        # '14:30'
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11112',
    },
    'select2': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11112',
    }
}

# Set the cache backend to select2
SELECT2_CACHE_BACKEND = 'select2'

# User Authentication
AUTHENTICATION_BACKENDS = (
    'userena.backends.UserenaAuthenticationBackend',
    'guardian.backends.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
)

ANONYMOUS_USER_ID = -1
AUTH_PROFILE_MODULE = 'accounts.UserProfile'
SITE_ID = 1

LOGIN_URL = '/accounts/signin/'
LOGOUT_URL = '/accounts/signout/'

USERENA_SIGNIN_REDIRECT_URL = '/'
USERENA_REDIRECT_ON_SIGNOUT = '/accounts/signin/'
USERENA_DISABLE_PROFILE_LIST = True
USERENA_ACTIVATION_REQUIRED = False
USERENA_DISABLE_SIGNUP = True
USERENA_USE_MESSAGES = False
USERENA_MUGSHOT_PATH = 'mugshots/%(username)s/'
USERENA_DEFAULT_PRIVACY = 'open'
USERENA_REGISTER_PROFILE = False

MEDIA_URL = '/media/'
MEDIA_ROOT = '/Users/Josh/PycharmProjects/clockwork-python/clockwork/static/media/'
