# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='privacy',
            field=models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='open', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy'),
        ),
    ]
