# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0003_auto_20181206_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaidsentity',
            name='digital_version_exists',
            field=models.BooleanField(default=False),
        ),
    ]
