# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0003_auto_20181206_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingaidsentity',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='findingaidsentity',
            name='language_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='findingaidsentity',
            name='language_statement_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='findingaidsentity',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='findingaidsentity',
            name='note_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='findingaidsentity',
            name='physical_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='findingaidsentity',
            name='physical_description_original',
            field=models.TextField(blank=True, null=True),
        ),
    ]
