# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-08 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0005_auto_20201019_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaidsentity',
            name='digital_version_exists',
            field=models.BooleanField(default=False),
        ),
    ]
