# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-12 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_aids', '0006_findingaidsentity_digital_version_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingaidsentity',
            name='digital_version_online',
            field=models.BooleanField(default=False),
        ),
    ]
