# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personotherformat',
            unique_together=set([('person', 'last_name', 'first_name')]),
        ),
    ]
